import type { Metadata } from "next";
import { Inter, Moulpali } from "next/font/google";
import React, { Suspense } from "react";
import Loading from "@/components/Loading";
import { Toaster } from "@/components/ui/sonner";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                {children}
                <Toaster />
            </body>

        </html>
    );
}
